# Generated by Django 2.1.7 on 2023-06-12 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230612_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 12, 20, 37, 43, 59342)),
        ),
    ]
